### PR TITLE
refactor and add doc

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by alerque** [comment]
Hey @Konfekt, thanks for taking the time to contribute to this project. I'm sorry it's taken so long to review this PR. The changes you make here make some sense and I would like to  get them organized and upstreamed. I am happy to do the work to fix the conflicts and bring things up to date. I can do this two ways:

1. Github actually allows me to push to your fork's master branch (since that is the one the PR is opened against). I can rebase that and update these commits in place. This has the advantage of using keeping this PR open and crediting you with it. It has the downside of messing with your personal fork which you may or may want to immediately use the changes I make.

2. Or I can open a feature branch somewhere else and cherry pick these commits and open a new PR. This has the downside of obsoleting this PR, but allows you to keep your own fork the way you like it.

Either way you'll be credited as the author of the commits. Let me know how you would prefer I proceed!

**Comment by Konfekt** [comment]
Hello @alerque, happy to see resparked interest in this PR. Let's go for the first option!

**Comment by alerque** [comment]
Oops, I botched that push by sending the wrong branch across. Let me see if I can figure out how to fix this.

**Comment by alerque** [comment]
Nope. I quite thoroughly shot myself in the foot there. Here's what happened:

1. Github allows project maintainers to push access to downstream branches that are opened as PR requests.
1. I rebased your master branch to get up to date and broke your commits up a bit.
1. I then pushed the canonical master branch to your master branch instead of the one I'd just rebased for you.
1. That closed the PR because the source and target branches were now the same.
1. With the PR closed, I now no longer have push access to the branch to push the correct branch!

For for convenience I have pushed two branches to this repo, one corresponding to your original master ([konfekt-backup](https://github.com/vim-pandoc/vim-markdownfootnotes/tree/konfekt-backup)) and one to the one I rebased and split ([konfekt](https://github.com/vim-pandoc/vim-markdownfootnotes/tree/konfekt)). You should be able to reset your own fork to whatever status you want by adding this repo as a remote, fetching all branches, then `git reset --hard <remote>/<branch>`. I apologize for the inconvenience.

In the mean time I'm going to open a PR to include the bits of that refactoring that I want to keep. For now I think that will be just the autoload, buffer, and documentation updates. I don't think I want to merge the changes to the default bindings without some discussion and that should be a separate PR.

**Comment by Konfekt** [comment]
> You should be able to reset your own fork to whatever status you want by adding this repo as a remote, fetching all branches, then git reset --hard <remote>/<branch>

I simply force pushed my repo to where it was before this hiccup.

> In the mean time I'm going to open a PR to include the bits of that refactoring that I want to keep. For now I think that will be just the autoload, buffer, and documentation updates. 

That's perfect

> I don't think I want to merge the changes to the default bindings without some discussion and that should be a separate PR.

That also makes perfect sense. Regarding the abbreviation introduced instead of the `<leader>` mapping in insert mode, it was meant as a less invasive convenient shortcut in insert mode that does not override printable characters such as `\`. Even though `\f` is perhaps not typed too often, it causes a lag on every `\`.

**Comment by alerque** [comment]
@Konfekt For similar reasons I also had my own bindings in my `init.vim` file, but I liked yours enough to actually rethink my own. I haven't settled on the same as yours, but the idea is good. I'm still inclined to open up another PR (maybe after 10 gets merged just to avoid commit clutter) with the change to open a discussion about the default usage & documentation of how to customize it.

**Pull request closed without merging**
