### PR TITLE
Refactor and document

### LINKED ISSUE #8: Document functions in vim's help format
The readme has a few notes on how to use this, but each function and mapping should also be properly document in the `:help` system.

### PR DESCRIPTION
**Pull request by alerque**
This is a replacement for PR #2 which I botched. These commits adapted from @Konfekt's master branch rebased on master (minus his key binding changes)...

1. Move all the function code into an autoload file and corresponding namespace
2. Set the mappings to be per buffer
3. Adds vim help documentation (this will fix #8).

### CODE REVIEW

**Comment by alerque** [comment]
I missed a few things the first time around but I think this is cleaned up and working again including the new auto-counter code. In reviewing it though it seems like there is some sloppy namespace things that could be cleared up. In particular shouldn't the footnote counter be a buffer scoped variable and not a global one? Maybe @Konfekt you could comment on that seeing as how you did some of the work to make mappings buffer scoped.

**Comment by Konfekt** [comment]
Yes, I agree that the footnote counter should be buffer-local and not global, for sure.

**Comment by alerque** [comment]
Thanks for the feedback @Konfekt. I was thinking to extend this refactor branch a bit with fixes for other scope issues and obsolete functions, but I started falling down a pretty big rabbit hole and am not sure when I'll get around to it all. I stepped back and reviewed just this much vs. the original and could not find any _regressions_, so I'm going to go ahead and merge this as is. That should make it easier for anybody else that comes along in the mean time to contribute without creating merge conflicts because of the major re-arrangement.

Thank you for the contribution!

**Comment by alerque** [comment]
By the way @Konfekt if you want an easy transition from your fork (and binding system) to the master again I've kept your commits rebased in the [`konfekt` branch](https://github.com/vim-pandoc/vim-markdownfootnotes/tree/konfekt), you can fetch and reset to that if you like.

**Comment by Konfekt** [comment]
> By the way @Konfekt if you want an easy transition from your fork (and binding system) to the master again I've kept your commits rebased in the konfekt branch, you can fetch and reset to that if you like.

Thanks! 

Regarding

> shouldn't the footnote counter be a buffer scoped variable and not a global one? 

that could also be merged in without much risk, should that become a different pull request?

**Comment by Konfekt** [comment]
Then there is the issue of the intrusive default mapping, particular in insert mode when people set `<leader>` to `,`; that could be discussed in a separate thread.

**Comment by alerque** [comment]
@Konfekt when I started looking at the scope of the counter variable I realized the auto-counter thing is basically obliterating the counter, obsoleting half the functions. I decided fixing that mess should be it's own kettle of fish and left the status quo for now.

I agree the default mapping is intrusive, mitigated by the fact that if you set your own custom mapping in your vim RC first, the plugin will not add it's own mapping at all. I kept your rebased branch around because I do want to launch a thread about what to do with the default bindings: both having less intrusive defaults and clearly documenting how to set your own would be improvements I think.

**Pull request merged**
